/**
 * 말레이시아 국제학교 카탈로그 (공개 정보 기반).
 *
 * 학교 정보(이름·설립 연도·위치·커리큘럼·공식 사이트)는 공개 사실.
 * 학비 범위는 2025-2026 시점 일반 시장 추정(USD/년) — 정확한 금액은 학교 공식 발표 확인.
 * 운영자 1차 방문·검증 데이터(operator_visited, 학생 국적 비율, 교사 국적 등)는
 * schools content collection 에 별도 누적 (현재 빈 상태).
 *
 * 운영자(데이비드)는 쿠알라룸푸르 거주 — 향후 직접 방문 후
 * "⭐ 운영자 방문 확인" 배지 부여 예정.
 */
import type { Locale } from './i18n';

export interface MyCurriculum {
  type: 'British' | 'American' | 'IB' | 'Australian' | 'Canadian' | 'Mixed';
  programs_en: string[]; // 예: ["IGCSE", "A-Level", "IB Diploma"]
}

export interface MalaysiaSchool {
  slug: string;
  name_en: string;
  name_ko: string;
  name_zh: string;
  abbreviation?: string;
  founded_year?: number;
  city_ko: string; // 예: '쿠알라룸푸르'
  city_zh: string;
  district_ko?: string;
  district_zh?: string;
  website: string;
  grade_range: string; // 예: "Year 1–13" 또는 "K–G12"
  curriculum: MyCurriculum;
  tuition_range_usd: [number, number]; // 연 학비 범위 USD
  boarding?: boolean; // 보딩 옵션 있음 여부
  highlights_ko: string[];
  highlights_zh: string[];
  summary_ko: string;
  summary_zh: string;
  /** 운영자가 직접 방문·검증 완료 시 true (현재 false 가 기본) */
  operator_visited?: boolean;
  /** 운영자 자녀 재학 학교 등 특수 표시 */
  operator_note_ko?: string;
  operator_note_zh?: string;
}

export const MALAYSIA_SCHOOLS: MalaysiaSchool[] = [
  {
    slug: 'alice-smith',
    name_en: 'The Alice Smith School',
    name_ko: '앨리스 스미스 스쿨',
    name_zh: '爱丽丝史密斯学校',
    abbreviation: 'KLASS', founded_year: 1946,
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Equine Park · Jalan Bellamy', district_zh: 'Equine Park · Jalan Bellamy',
    website: 'https://www.alice-smith.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['EYFS', 'IGCSE', 'A-Level'] },
    tuition_range_usd: [25000, 35000],
    highlights_ko: [
      '말레이시아 최초·최고(最古) 영국식 국제학교 (1946 설립)',
      'COBIS(Council of British International Schools) 정회원',
      'Equine Park(초등) + Jalan Bellamy(중·고등) 2캠퍼스 운영',
      'A-Level 정통 트랙 — 옥스브리지 진학 사례 정기 배출',
      '비영리 운영, 부모 회원 거버넌스',
    ],
    highlights_zh: [
      '马来西亚最古老英式国际学校(1946 创立)',
      'COBIS(英国海外学校理事会)正会员',
      'Equine Park(小学)+ Jalan Bellamy(中学)双校区',
      'A-Level 正统路径 — 牛剑录取案例稳定产出',
      '非营利 · 家长董事治理',
    ],
    summary_ko: '1946년 설립된 말레이시아 영국식 국제학교의 표준. KL 도심 2캠퍼스(초등·중고등 분리). A-Level 정통 트랙으로 옥스브리지 진학 사례 정기.',
    summary_zh: '1946 年创立的马来西亚英式国际学校标杆。吉隆坡市区双校区(小学·中学分离),A-Level 正统路径,牛剑录取案例稳定。',
  },
  {
    slug: 'iskl',
    name_en: 'International School of Kuala Lumpur',
    name_ko: 'ISKL — 쿠알라룸푸르 국제학교',
    name_zh: 'ISKL — 吉隆坡国际学校',
    abbreviation: 'ISKL', founded_year: 1965,
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Ampang Jaya', district_zh: 'Ampang Jaya',
    website: 'https://www.iskl.edu.my',
    grade_range: 'K–G12',
    curriculum: { type: 'American', programs_en: ['American', 'IB Diploma', 'AP'] },
    tuition_range_usd: [23000, 33000],
    highlights_ko: [
      '말레이시아 최대 미국식 국제학교 (1965 설립)',
      'WASC 인증 + IB World School',
      '비영리 운영',
      '50+ 국적, 1,500+ 학생',
      '대학 진학 카운슬링 강점 — 미국·옥스브리지 진학 매년 배출',
    ],
    highlights_zh: [
      '马来西亚最大美式国际学校(1965 创立)',
      'WASC 认证 + IB World School',
      '非营利运营',
      '50+ 国籍,1,500+ 学生',
      '升学辅导优势 — 美国·牛剑录取每年产出',
    ],
    summary_ko: 'KL 최대 미국식 국제학교. Ampang Jaya 캠퍼스, IB + AP 동시 운영, 50+ 국적 다국적 환경. WASC + IB World 이중 인증.',
    summary_zh: '吉隆坡最大美式国际学校。Ampang Jaya 校园,IB + AP 并行,50+ 国籍。WASC + IB World 双认证。',
  },
  {
    slug: 'mkis',
    name_en: "Mont'Kiara International School",
    name_ko: '몽키아라 국제학교',
    name_zh: '满家乐国际学校',
    abbreviation: 'MKIS', founded_year: 1994,
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Mont\'Kiara', district_zh: '满家乐',
    website: 'https://www.mkis.edu.my',
    grade_range: 'PreK–G12',
    curriculum: { type: 'American', programs_en: ['American', 'IB Diploma'] },
    tuition_range_usd: [22000, 30000],
    highlights_ko: [
      'Mont\'Kiara 한인·중국·일본 학부모 거주 밀집 지역 중심',
      '미국식 + IB Diploma',
      'WASC + IB World School',
      '한국 학부모 커뮤니티 비교적 활발',
      '학교 안에 다양한 클럽·스포츠 시설',
    ],
    highlights_zh: [
      '位于满家乐韩 · 中 · 日家长聚居区',
      '美式 + IB Diploma',
      'WASC + IB World School',
      '韩国家长社区相对活跃',
      '丰富的课外社团与体育设施',
    ],
    summary_ko: 'Mont\'Kiara 중심부 위치, 한국·중국·일본 학부모 거주 밀집 지역. 미국식 + IB. 한국 학부모 커뮤니티 비교적 활발한 학교.',
    summary_zh: '位于满家乐核心,韩 · 中 · 日家长聚居区。美式 + IB,韩国家长社区相对活跃。',
  },
  {
    slug: 'gis',
    name_en: 'Garden International School',
    name_ko: '가든 국제학교',
    name_zh: '花园国际学校',
    abbreviation: 'GIS', founded_year: 1951,
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Mont\'Kiara', district_zh: '满家乐',
    website: 'https://www.gardenschool.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level', 'IB Diploma'] },
    tuition_range_usd: [18000, 28000],
    highlights_ko: [
      '1951년 설립, 말레이시아 영국식 국제학교 중 가장 오래된 학교 중 하나',
      'Mont\'Kiara 캠퍼스 — 큰 규모',
      'IGCSE → A-Level / IB Diploma 둘 다 선택 가능',
      'Taylor\'s Education Group 운영',
      '60+ 국적',
    ],
    highlights_zh: [
      '1951 年创立,马来西亚最古老英式国际学校之一',
      '满家乐校园 — 大规模',
      'IGCSE → A-Level / IB Diploma 双选',
      'Taylor\'s 教育集团运营',
      '60+ 国籍',
    ],
    summary_ko: '1951년 설립 영국식 학교. Mont\'Kiara 대규모 캠퍼스, A-Level + IB 병행. Taylor\'s 그룹 운영, 60+ 국적.',
    summary_zh: '1951 年创立的英式学校。满家乐大型校园,A-Level + IB 并行,Taylor\'s 集团运营,60+ 国籍。',
  },
  {
    slug: 'epsom-college',
    name_en: 'Epsom College in Malaysia',
    name_ko: '엡솜 칼리지 말레이시아',
    name_zh: '马来西亚爱普索学院',
    abbreviation: 'Epsom', founded_year: 2014,
    city_ko: '네그리 셈빌란', city_zh: '森美兰',
    district_ko: 'Bandar Enstek (KLIA 인근)', district_zh: 'Bandar Enstek(KLIA 附近)',
    website: 'https://www.epsomcollege.edu.my',
    grade_range: 'Year 5–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level'] },
    tuition_range_usd: [23000, 32000],
    boarding: true,
    highlights_ko: [
      '영국 Epsom College (1855) 자매 학교',
      '말레이시아 최초 본격 영국식 보딩스쿨',
      'KLIA 공항 인근 50에이커 캠퍼스',
      '보딩(기숙) + 데이 옵션',
      'A-Level 진학 트랙 — 영국 명문대 표적',
    ],
    highlights_zh: [
      '英国 Epsom College(1855)姐妹校',
      '马来西亚首所正统英式寄宿学校',
      'KLIA 机场附近 50 英亩校园',
      '寄宿 + 走读',
      'A-Level 升学路径 — 瞄准英国名校',
    ],
    summary_ko: '영국 Epsom College 자매 학교, 말레이시아 최초 본격 영국식 보딩. KLIA 인근 50에이커 캠퍼스, A-Level 정통.',
    summary_zh: '英国 Epsom College 姐妹校,马来西亚首所正统英式寄宿学校。KLIA 附近 50 英亩校园,A-Level 正统。',
  },
  {
    slug: 'bskl',
    name_en: 'British School of Kuala Lumpur',
    name_ko: 'BSKL — 영국식 쿠알라룸푸르 국제학교',
    name_zh: 'BSKL — 吉隆坡英国学校',
    abbreviation: 'BSKL', founded_year: 2009,
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Subang Jaya', district_zh: '梳邦再也',
    website: 'https://www.britishschool.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level', 'IB Diploma'] },
    tuition_range_usd: [18000, 26000],
    highlights_ko: [
      'Nord Anglia Education 글로벌 네트워크',
      '영국식 (IGCSE → A-Level) + IB Diploma 둘 다',
      'Subang Jaya 캠퍼스',
      'Nord Anglia 80+ 학교 글로벌 연계 (교환 프로그램)',
      'STEAM 강점',
    ],
    highlights_zh: [
      'Nord Anglia 教育全球网络',
      '英式(IGCSE → A-Level)+ IB Diploma 双选',
      '梳邦再也校园',
      '与 Nord Anglia 80+ 全球学校联动(交换项目)',
      'STEAM 强项',
    ],
    summary_ko: 'Nord Anglia 글로벌 네트워크의 KL 캠퍼스. 영국식 + IB 둘 다 선택 가능, Subang Jaya 위치, STEAM 강점.',
    summary_zh: 'Nord Anglia 全球网络的吉隆坡校园。英式 + IB 双选,位于梳邦再也,STEAM 优势。',
  },
  {
    slug: 'igb',
    name_en: 'IGB International School',
    name_ko: 'IGB 국제학교',
    name_zh: 'IGB 国际学校',
    abbreviation: 'IGBIS', founded_year: 2014,
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Sierramas, Sungai Buloh', district_zh: 'Sierramas, Sungai Buloh',
    website: 'https://www.igbis.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'IB', programs_en: ['IB PYP', 'IB MYP', 'IB Diploma'] },
    tuition_range_usd: [17000, 25000],
    highlights_ko: [
      'IB 전 단계 인증 (PYP · MYP · DP 모두)',
      'Sierramas 자연 환경 캠퍼스',
      'IB 학교로는 말레이시아 비교적 신규(2014)',
      '소규모 학급 운영',
      'IGB(Tan Sri Robert Tan) 그룹 운영',
    ],
    highlights_zh: [
      'IB 全阶段认证(PYP · MYP · DP)',
      'Sierramas 自然环境校园',
      '在马来西亚相对新(2014)的 IB 学校',
      '小班教学',
      'IGB(陈志远集团)运营',
    ],
    summary_ko: '2014 개교, IB 전 단계 (PYP · MYP · DP) 인증. Sungai Buloh Sierramas 자연 환경 캠퍼스, 소규모 학급.',
    summary_zh: '2014 开校,IB 全阶段(PYP · MYP · DP)认证。Sungai Buloh Sierramas 自然校园,小班教学。',
  },
  {
    slug: 'sjim',
    name_en: 'St. Joseph\'s Institution International Malaysia',
    name_ko: 'SJIM — 세인트조셉 국제학교',
    name_zh: 'SJIM — 圣若瑟书院国际',
    abbreviation: 'SJIM',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Tropicana, Petaling Jaya', district_zh: 'Tropicana, Petaling Jaya',
    website: 'https://www.sjiinternational.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'Mixed', programs_en: ['IGCSE', 'IB Diploma'] },
    tuition_range_usd: [16000, 24000],
    highlights_ko: [
      '싱가포르 St. Joseph\'s Institution (1852) 자매 학교',
      'Lasallian 가톨릭 미션 (비가톨릭 입학 가능)',
      'Tropicana 캠퍼스',
      'IGCSE + IB Diploma',
      '인성·봉사 활동 비중 높음',
    ],
    highlights_zh: [
      '新加坡 St. Joseph\'s Institution(1852)姐妹校',
      '拉萨修会天主教使命学校(非教徒可入读)',
      'Tropicana 校园',
      'IGCSE + IB Diploma',
      '注重品格 · 服务活动',
    ],
    summary_ko: '싱가포르 SJI 자매 학교, Lasallian 가톨릭 미션. Tropicana PJ 캠퍼스, IGCSE + IB, 인성·봉사 강점.',
    summary_zh: '新加坡 SJI 姐妹校,拉萨修会天主教使命。Tropicana PJ 校园,IGCSE + IB,注重品格 · 服务。',
  },
  {
    slug: 'nexus',
    name_en: 'Nexus International School Putrajaya',
    name_ko: '넥서스 국제학교 푸트라자야',
    name_zh: 'Nexus 国际学校 布城',
    abbreviation: 'Nexus', founded_year: 2008,
    city_ko: '푸트라자야', city_zh: '布城',
    district_ko: 'Presint 16, Putrajaya', district_zh: '布城 16 区',
    website: 'https://www.nexus.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'IB', programs_en: ['IB PYP', 'IB MYP', 'IB Diploma'] },
    tuition_range_usd: [15000, 23000],
    boarding: true,
    highlights_ko: [
      'Taylor\'s Education Group 운영',
      'Putrajaya 위치 — 정부 청사·외교 지역',
      'IB 전 단계 + 보딩 옵션',
      'Cognita 그룹과 협력',
      '대형 캠퍼스 + 첨단 시설',
    ],
    highlights_zh: [
      'Taylor\'s 教育集团运营',
      '布城位置 — 政府 · 外交区',
      'IB 全阶段 + 寄宿选项',
      '与 Cognita 集团合作',
      '大型校园 + 先进设施',
    ],
    summary_ko: 'Taylor\'s 그룹 운영, Putrajaya 위치. IB 전 단계 + 보딩 옵션, 정부 청사 지역 외교관 자녀 비율 일정 수준.',
    summary_zh: 'Taylor\'s 集团运营,布城位置。IB 全阶段 + 寄宿,政府区外交官子女比例稳定。',
  },
  {
    slug: 'sunway',
    name_en: 'Sunway International School',
    name_ko: '썬웨이 국제학교',
    name_zh: '双威国际学校',
    abbreviation: 'SIS',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Bandar Sunway', district_zh: 'Bandar Sunway',
    website: 'https://international-school.sunway.edu.my',
    grade_range: 'Grade 7–12',
    curriculum: { type: 'Canadian', programs_en: ['Ontario Secondary School Diploma (OSSD)'] },
    tuition_range_usd: [12000, 18000],
    highlights_ko: [
      '캐나다 온타리오 OSSD 커리큘럼 — 말레이시아 거의 유일',
      'Sunway 종합 캠퍼스 (대학·병원·쇼핑몰 연계)',
      '중·고등(Grade 7-12) 전용 — 초등 X',
      '캐나다 대학 진학 직접 트랙',
      '학비 가성비',
    ],
    highlights_zh: [
      '加拿大安省 OSSD 课程 — 马来西亚几乎独家',
      '双威综合校园(大学 · 医院 · 商场联动)',
      '仅初中 · 高中(7-12 年级),不招小学',
      '加拿大大学升学直通',
      '学费高性价比',
    ],
    summary_ko: '캐나다 온타리오 OSSD 학교, Sunway City 종합 캠퍼스. 중·고등만 운영, 캐나다 대학 진학 직결 + 학비 가성비.',
    summary_zh: '加拿大安省 OSSD 学校,双威综合校园。仅 7-12 年级,加拿大大学直通 + 学费高性价比。',
  },
  {
    slug: 'isp',
    name_en: 'International School @ ParkCity',
    name_ko: 'ISP — 파크시티 국제학교',
    name_zh: 'ISP — ParkCity 国际学校',
    abbreviation: 'ISP',
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Desa ParkCity', district_zh: 'Desa ParkCity',
    website: 'https://www.isparkcity.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level', 'IB Diploma'] },
    tuition_range_usd: [14000, 22000],
    highlights_ko: [
      'Desa ParkCity 신도시 핵심 위치',
      '영국식 + IB 둘 다 선택 가능',
      '주변 공원·반려동물 친화 커뮤니티',
      'IGCSE → A-Level / IB Diploma 분기',
      '중간 규모 (한 학년 100명대)',
    ],
    highlights_zh: [
      'Desa ParkCity 新城核心位置',
      '英式 + IB 双选',
      '周边公园 · 宠物友好社区',
      'IGCSE → A-Level / IB 分流',
      '中等规模(每年级约 100 人)',
    ],
    summary_ko: 'Desa ParkCity 신도시 핵심에 위치, 영국식 + IB. 가족 친화 커뮤니티 환경, IGCSE → A-Level/IB 분기 선택.',
    summary_zh: '位于 Desa ParkCity 新城核心,英式 + IB。家庭友好社区,IGCSE → A-Level/IB 分流。',
  },
  {
    slug: 'aism',
    name_en: 'Australian International School Malaysia',
    name_ko: 'AISM — 호주 국제학교',
    name_zh: 'AISM — 澳大利亚国际学校',
    abbreviation: 'AISM',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Saujana, Subang', district_zh: 'Saujana, Subang',
    website: 'https://www.aism.edu.my',
    grade_range: 'K–Year 12',
    curriculum: { type: 'Australian', programs_en: ['NSW Curriculum', 'HSC'] },
    tuition_range_usd: [13000, 21000],
    highlights_ko: [
      '호주 NSW 커리큘럼 (HSC 트랙)',
      '호주 대학 진학 직접 적합',
      '말레이시아 거의 유일한 본격 호주식 학교',
      'Saujana 골프장 인근 캠퍼스',
      '호주 G8 진학 트랙',
    ],
    highlights_zh: [
      '澳大利亚新南威尔士州课程(HSC 路径)',
      '直通澳大利亚大学申请',
      '马来西亚几乎唯一正统澳式学校',
      'Saujana 高尔夫附近校园',
      '澳大利亚八大升学路径',
    ],
    summary_ko: '호주 NSW 커리큘럼 HSC 트랙. 말레이시아 거의 유일한 본격 호주식 학교, 호주 G8 대학 직접 진학.',
    summary_zh: '澳大利亚新南威尔士州课程 HSC。马来西亚几乎唯一正统澳式,直通八大。',
  },
  {
    slug: 'oasis',
    name_en: 'Oasis International School Kuala Lumpur',
    name_ko: '오아시스 국제학교',
    name_zh: '绿洲国际学校',
    abbreviation: 'OIS',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Kajang (KL 남쪽)', district_zh: 'Kajang(吉隆坡南)',
    website: 'https://www.oasisinternationalschool.edu.my',
    grade_range: 'K–G12',
    curriculum: { type: 'American', programs_en: ['American', 'AP'] },
    tuition_range_usd: [9000, 16000],
    highlights_ko: [
      'Kajang 위치 — KL 남부 학부모용',
      '미국식 + AP',
      '학비 가성비',
      '중간 규모 — 학년당 학생 적정',
      '미국 대학 진학 트랙',
    ],
    highlights_zh: [
      'Kajang 位置 — 吉隆坡南部家长适配',
      '美式 + AP',
      '学费高性价比',
      '中等规模 — 每年级学生适度',
      '美国大学升学路径',
    ],
    summary_ko: 'Kajang 위치 (KL 남부), 미국식 + AP. 학비 가성비 + 미국 대학 진학 트랙.',
    summary_zh: 'Kajang(吉隆坡南),美式 + AP。学费高性价比 + 美国大学升学。',
  },
  {
    slug: 'sri-kdu-kota-damansara',
    name_en: 'Sri KDU International School',
    name_ko: 'Sri KDU 국제학교 (코타다만사라)',
    name_zh: 'Sri KDU 国际学校(哥打白沙罗)',
    abbreviation: 'Sri KDU',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Kota Damansara', district_zh: '哥打白沙罗',
    website: 'https://www.srikdu.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level', 'IB Diploma'] },
    tuition_range_usd: [12000, 20000],
    highlights_ko: [
      'Kota Damansara 캠퍼스 (말레이시아 학부모 거주 지역)',
      '영국식 IGCSE → A-Level + IB Diploma',
      'Sri KDU 그룹 (말레이시아 사립학교 그룹)',
      '말레이시아 + 외국인 학생 혼합 환경',
      '학비 가성비',
    ],
    highlights_zh: [
      '哥打白沙罗校园(本地家长居住区)',
      '英式 IGCSE → A-Level + IB Diploma',
      'Sri KDU 集团(马来西亚私校集团)',
      '本地 + 外籍学生混合环境',
      '学费高性价比',
    ],
    summary_ko: 'Kota Damansara 캠퍼스, 영국식 + IB. Sri KDU 그룹, 말레이시아 학부모 거주지 중심 학교.',
    summary_zh: '哥打白沙罗校园,英式 + IB。Sri KDU 集团,位于本地家长聚居区。',
  },
  {
    slug: 'peninsula',
    name_en: 'Peninsula International School Australia',
    name_ko: '페닌슐라 호주 국제학교',
    name_zh: 'Peninsula 澳大利亚国际学校',
    abbreviation: 'PISA',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Setia Eco Park, Shah Alam', district_zh: 'Setia Eco Park, 莎阿南',
    website: 'https://www.peninsula.edu.my',
    grade_range: 'K–Year 12',
    curriculum: { type: 'Australian', programs_en: ['Victoria Curriculum', 'VCE'] },
    tuition_range_usd: [7000, 13000],
    highlights_ko: [
      '호주 빅토리아 커리큘럼 (VCE 트랙)',
      'Setia Eco Park 친환경 신도시',
      '학비 가성비 — AISM 대비 30~40% 저렴',
      '소규모 학교',
      '호주 멜번대·G8 진학 트랙',
    ],
    highlights_zh: [
      '澳大利亚维多利亚州课程(VCE)',
      'Setia Eco Park 环保新城',
      '学费比 AISM 低 30~40%',
      '小规模学校',
      '澳大利亚墨大 · 八大升学路径',
    ],
    summary_ko: '호주 빅토리아 VCE 트랙, Setia Eco Park 위치. AISM 대비 가성비 호주식 학교.',
    summary_zh: '澳大利亚维多利亚州 VCE,Setia Eco Park 校园。比 AISM 性价比更高的澳式学校。',
  },
  {
    slug: 'tenby-setia-eco-park',
    name_en: 'Tenby International School Setia EcoPark',
    name_ko: '텐비 국제학교 (세티아 에코파크)',
    name_zh: 'Tenby 国际学校(Setia EcoPark)',
    abbreviation: 'Tenby',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Setia Eco Park, Shah Alam', district_zh: 'Setia Eco Park, 莎阿南',
    website: 'https://tenby.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level'] },
    tuition_range_usd: [8000, 15000],
    highlights_ko: [
      'Cognita Schools (영국) 글로벌 그룹',
      '말레이시아 다중 캠퍼스 (Setia Eco Park · Tropicana · Penang · Ipoh)',
      '영국식 + 말레이시아 국가 커리큘럼 병행 옵션',
      '학비 중간~가성비 구간',
      '신도시 가족 친화 환경',
    ],
    highlights_zh: [
      'Cognita Schools(英国)全球集团',
      '马来西亚多校区(Setia Eco Park · Tropicana · 槟城 · 怡保)',
      '英式 + 马来西亚国家课程并行选项',
      '中等 ~ 高性价比学费',
      '新城家庭友好环境',
    ],
    summary_ko: 'Cognita 영국 그룹의 말레이시아 다중 캠퍼스 중 Setia Eco Park 캠퍼스. 영국식 정통 + 가성비.',
    summary_zh: 'Cognita 英国集团马来多校区中 Setia Eco Park 校园。英式正统 + 高性价比。',
  },
  {
    slug: 'help-international',
    name_en: 'HELP International School',
    name_ko: '헬프 국제학교',
    name_zh: 'HELP 国际学校',
    abbreviation: 'HIS',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Subang Bestari', district_zh: 'Subang Bestari',
    website: 'https://www.help-is.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level'] },
    tuition_range_usd: [8000, 14000],
    highlights_ko: [
      'HELP University 그룹의 자매 학교',
      'Subang Bestari 캠퍼스',
      '영국식 (IGCSE + A-Level)',
      '학비 가성비',
      'HELP 대학과 연계 진학 가능',
    ],
    highlights_zh: [
      'HELP 大学集团姐妹校',
      'Subang Bestari 校园',
      '英式(IGCSE + A-Level)',
      '学费高性价比',
      '可与 HELP 大学衔接升学',
    ],
    summary_ko: 'HELP University 그룹 자매 학교. Subang Bestari 위치, 영국식 + 가성비. HELP 대학 연계.',
    summary_zh: 'HELP 大学集团姐妹校。位于 Subang Bestari,英式 + 高性价比,可衔接 HELP 大学。',
  },
  {
    slug: 'ucsi-kl',
    name_en: 'UCSI International School Kuala Lumpur',
    name_ko: 'UCSI 국제학교 쿠알라룸푸르',
    name_zh: 'UCSI 国际学校 吉隆坡',
    abbreviation: 'UCSI KL', founded_year: 2010,
    city_ko: '쿠알라룸푸르', city_zh: '吉隆坡',
    district_ko: 'Cheras / Springhill', district_zh: 'Cheras / Springhill',
    website: 'https://www.ucsiinternationalschool.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['Cambridge IGCSE', 'A-Level'] },
    tuition_range_usd: [6000, 15000],
    highlights_ko: [
      'UCSI 대학·교육 그룹의 국제학교',
      'Cheras (KL) + Springhill (Port Dickson 인근) 2캠퍼스',
      'Cambridge IGCSE + A-Level 영국식',
      '말레이시아 국제학교 중 가성비 구간',
      'UCSI 대학으로 자연스러운 연계 진학',
    ],
    highlights_zh: [
      'UCSI 大学 · 教育集团旗下国际学校',
      'Cheras(吉隆坡)+ Springhill(波德申附近)双校区',
      'Cambridge IGCSE + A-Level 英式',
      '马来西亚国际学校中的高性价比段',
      '可衔接 UCSI 大学升学',
    ],
    summary_ko: 'UCSI 그룹 자매 학교. Cheras + Springhill 2캠퍼스, Cambridge 영국식, 가성비 구간. UCSI 대학 연계.',
    summary_zh: 'UCSI 集团姐妹校。Cheras + Springhill 双校区,Cambridge 英式,高性价比段。可衔接 UCSI 大学。',
    operator_note_ko: '운영자(데이비드) 자녀 재학 학교. 운영자 1차 경험·방문 검증 데이터는 별도 업데이트 예정.',
    operator_note_zh: '站长 David 子女在读学校。站长亲身经验 · 走访核实数据后续单独更新。',
  },
  {
    slug: 'apis',
    name_en: 'Asia Pacific International School Malaysia',
    name_ko: 'APIS — 아시아 퍼시픽 국제학교',
    name_zh: 'APIS — 亚太国际学校',
    abbreviation: 'APIS',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Selangor', district_zh: '雪兰莪',
    website: 'https://www.apis.edu.my',
    grade_range: 'K–G12',
    curriculum: { type: 'American', programs_en: ['American', 'AP'] },
    tuition_range_usd: [10000, 17000],
    highlights_ko: [
      '미국식 + AP',
      'Selangor 위치 (학교 공식 사이트에서 정확 캠퍼스 확인)',
      '학비 중간 ~ 가성비 구간',
      '미국 대학 진학 트랙',
      '소규모 학교',
    ],
    highlights_zh: [
      '美式 + AP',
      '位于雪兰莪(具体校区请查阅官网)',
      '中等 ~ 高性价比学费',
      '美国大学升学路径',
      '小规模学校',
    ],
    summary_ko: '미국식 + AP, Selangor 위치, 학비 가성비 구간. 미국 대학 진학 트랙 + 소규모 학교.',
    summary_zh: '美式 + AP,位于雪兰莪,学费高性价比段。美国大学升学 + 小规模。',
  },
  {
    slug: 'straits-rawang',
    name_en: 'The Straits International School Rawang',
    name_ko: '스트레이츠 국제학교 라왕',
    name_zh: 'Straits 国际学校 万挠',
    abbreviation: 'Straits',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Rawang', district_zh: '万挠',
    website: 'https://www.straits.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level'] },
    tuition_range_usd: [6000, 12000],
    highlights_ko: [
      'Rawang 위치 (Selangor 북부, KL 외곽)',
      '영국식 IGCSE + A-Level',
      '학비 가성비 구간 (KL 도심 대비 30~40% 저렴)',
      '소규모 학교',
      '셀랑고르 북부·페낭 학부모 통학 가능',
    ],
    highlights_zh: [
      'Rawang 位置(雪兰莪北部,吉隆坡郊外)',
      '英式 IGCSE + A-Level',
      '学费比吉隆坡市区便宜 30~40%',
      '小规模学校',
      '雪兰莪北部 · 槟城家长可通学',
    ],
    summary_ko: 'Rawang 위치, 영국식 + 가성비. KL 도심 대비 학비 30~40% 저렴, 소규모 학교.',
    summary_zh: 'Rawang 位置,英式 + 高性价比。比吉隆坡市区便宜 30~40%,小规模。',
  },
  {
    slug: 'sri-bestari',
    name_en: 'Sri Bestari International School',
    name_ko: '스리 베스타리 국제학교',
    name_zh: 'Sri Bestari 国际学校',
    abbreviation: 'SBIS',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Subang Bestari', district_zh: 'Subang Bestari',
    website: 'https://www.sribestari.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['IGCSE', 'A-Level'] },
    tuition_range_usd: [7000, 12000],
    highlights_ko: [
      'Subang Bestari 캠퍼스',
      '영국식 (IGCSE + A-Level)',
      '학비 가성비',
      '말레이시아 학부모 비율 높음',
      '소규모 학교',
    ],
    highlights_zh: [
      'Subang Bestari 校园',
      '英式(IGCSE + A-Level)',
      '学费高性价比',
      '本地家长比例较高',
      '小规模学校',
    ],
    summary_ko: 'Subang Bestari 위치, 영국식 + 가성비. 말레이시아 학부모 비율 높은 학교.',
    summary_zh: 'Subang Bestari 校园,英式 + 高性价比。本地家长比例较高。',
  },
  {
    slug: 'ucsi-subang',
    name_en: 'UCSI International School Subang Jaya',
    name_ko: 'UCSI 국제학교 수방자야',
    name_zh: 'UCSI 国际学校 梳邦再也',
    abbreviation: 'UCSI Subang',
    city_ko: '셀랑고르', city_zh: '雪兰莪',
    district_ko: 'Subang Jaya', district_zh: '梳邦再也',
    website: 'https://www.ucsiinternationalschool.edu.my',
    grade_range: 'Year 1–13',
    curriculum: { type: 'British', programs_en: ['Cambridge IGCSE', 'A-Level'] },
    tuition_range_usd: [7000, 14000],
    highlights_ko: [
      'UCSI 그룹의 Subang Jaya 신규 캠퍼스',
      'Cambridge IGCSE + A-Level',
      'UCSI KL · Springhill 캠퍼스와 동일 그룹',
      'Subang 거주 학부모용 옵션',
      '학비 가성비',
    ],
    highlights_zh: [
      'UCSI 集团梳邦再也新校区',
      'Cambridge IGCSE + A-Level',
      '与 UCSI KL · Springhill 校区同集团',
      'Subang 居住家长适配',
      '学费高性价比',
    ],
    summary_ko: 'UCSI 그룹의 Subang Jaya 신규 캠퍼스. Cambridge 영국식, 가성비, UCSI 그룹 자매 학교.',
    summary_zh: 'UCSI 集团梳邦再也新校区。Cambridge 英式,高性价比,UCSI 集团姐妹校。',
  },
];

export function getMalaysiaSchool(slug: string): MalaysiaSchool | undefined {
  return MALAYSIA_SCHOOLS.find((s) => s.slug === slug);
}

export function malaysiaSchoolName(s: MalaysiaSchool, locale: Locale): string {
  return locale === 'ko' ? s.name_ko : s.name_zh;
}
