/**
 * 학교별 원어민 교사 비율 데이터.
 *
 * 출처 분류:
 *  - 'official': 학교 공식 사이트·마케팅 자료에 명시된 수치 (예: "80% UK/US qualified teachers")
 *  - 'community': 한국·중국 학부모 커뮤니티 청취 (재학생·졸업생 후기 평균)
 *  - 'estimated': 학비 등급 기반 추정 (deriveFinance 폴백) — 본 파일에 없는 학교
 *
 * '원어민(Native English Speaker)'의 정의:
 *  - 영어 모국어 국가: 영국·미국·캐나다·호주·뉴질랜드·아일랜드
 *  - 인도·필리핀·싱가포르 영어 가능 교사는 별도 카운트 (포함 안 함)
 *
 * 본 수치는 학교 등록비 안내·마케팅 자료·학부모 후기 종합. 실제 비율은
 * 학년·과목별 큰 차이가 있으며, 연도별 변동 — 정확한 최신은 학교 입학설명회 확인.
 */

export interface NativeTeacherData {
  ratio: number; // 0~100
  source: 'official' | 'community';
  note_ko?: string;
  note_zh?: string;
}

export const NATIVE_TEACHER_RATIOS: Record<string, NativeTeacherData> = {
  // ─── 말레이시아 ────────────────────────────────────────────────
  'alice-smith': { ratio: 85, source: 'official',
    note_ko: '대부분 영국 PGCE 자격 교사. UK·영연방 국적 다수.',
    note_zh: '多数英国 PGCE 资格教师。英国 · 英联邦籍占多。' },
  'iskl': { ratio: 78, source: 'official',
    note_ko: '미국 본토·캐나다 다수. 미국식 K-12 인증.',
    note_zh: '美国本土 · 加拿大占多。美式 K-12 认证。' },
  'mkis': { ratio: 75, source: 'community',
    note_ko: '미국·캐나다·UK 다수. IB·AP 트랙.',
    note_zh: '美国 · 加拿大 · 英国占多。IB · AP 路径。' },
  'gis': { ratio: 80, source: 'official',
    note_ko: '영국 UK 다수. Cambridge·IB 트랙 분리.',
    note_zh: '英国占多。Cambridge · IB 双路径。' },
  'epsom-college': { ratio: 88, source: 'official',
    note_ko: '영국 본교 교사 파견 다수. 보딩 하우스마스터 UK 자격.',
    note_zh: '英国总校派遣教师多。寄宿舍监持 UK 资格。' },
  'bskl': { ratio: 75, source: 'official',
    note_ko: '영국·호주 UK 자격 교사 중심.',
    note_zh: '英国 · 澳大利亚 UK 资格教师为主。' },
  'igb': { ratio: 65, source: 'community',
    note_ko: 'IB World School. 영·호·캐 + 말레이 현지 혼합.',
    note_zh: 'IB World School。英澳加 + 马来本地混合。' },
  'sjim': { ratio: 55, source: 'community',
    note_ko: '싱가포르 St Joseph\'s 자매. 싱가포르·말레이·UK 혼합.',
    note_zh: '新加坡 St Joseph\'s 姊妹校。新加坡 · 马来 · 英国混合。' },
  'nexus': { ratio: 72, source: 'official',
    note_ko: '영국 Taylor\'s 그룹. IB 인증 교사 다수.',
    note_zh: '英国 Taylor\'s 集团。IB 认证教师多。' },
  'sunway': { ratio: 50, source: 'community',
    note_ko: 'Sunway 그룹. UK 자격 + 말레이 현지 혼합.',
    note_zh: 'Sunway 集团。UK 资格 + 马来本地混合。' },
  'isp': { ratio: 70, source: 'community',
    note_ko: 'Desa ParkCity. 영국·호주·캐나다 다수. Cambridge.',
    note_zh: 'Desa ParkCity。英澳加占多。Cambridge。' },
  'aism': { ratio: 65, source: 'official',
    note_ko: '호주 NSW 자격 교사 중심.',
    note_zh: '澳大利亚 NSW 资格教师为主。' },
  'oasis': { ratio: 35, source: 'community',
    note_ko: 'Kajang. 말레이·필리핀·인도 영어 교사 다수.',
    note_zh: '加影。马来 · 菲律宾 · 印度英语教师多。' },
  'sri-kdu-kota-damansara': { ratio: 50, source: 'community',
    note_ko: 'Cambridge 영국식. UK 자격 + 현지 혼합.',
    note_zh: 'Cambridge 英式。UK 资格 + 本地混合。' },
  'peninsula': { ratio: 55, source: 'community',
    note_ko: '호주식 PISA. 호주·말레이 혼합.',
    note_zh: '澳式 PISA。澳大利亚 · 马来混合。' },
  'tenby-setia-eco-park': { ratio: 45, source: 'community',
    note_ko: 'Tenby 그룹. Cambridge 자격 + 현지 혼합.',
    note_zh: 'Tenby 集团。Cambridge 资格 + 本地混合。' },
  'help-international': { ratio: 40, source: 'community',
    note_ko: 'HELP 그룹. 현지 + 인도·필리핀 영어 교사 다수.',
    note_zh: 'HELP 集团。本地 + 印度 · 菲律宾英语教师多。' },
  'ucsi-kl': { ratio: 50, source: 'community',
    note_ko: '⭐ 운영자 자녀 재학. Cambridge 영국식. UK 자격 + 현지 혼합.',
    note_zh: '⭐ 站长子女在读。Cambridge 英式。UK 资格 + 本地混合。' },
  'apis': { ratio: 30, source: 'community',
    note_ko: '한국 운영. 한국·미국·필리핀 영어 교사 혼합.',
    note_zh: '韩国运营。韩国 · 美国 · 菲律宾英语教师混合。' },
  'straits-rawang': { ratio: 35, source: 'community',
    note_ko: 'Rawang 신도시. Cambridge + 현지 혼합.',
    note_zh: 'Rawang 新城。Cambridge + 本地混合。' },
  'sri-bestari': { ratio: 30, source: 'community',
    note_ko: 'Subang Bestari. 현지·인도·필리핀 영어 교사 다수.',
    note_zh: 'Subang Bestari。本地 · 印度 · 菲律宾英语教师多。' },
  'ucsi-subang': { ratio: 45, source: 'community',
    note_ko: 'UCSI 그룹 신캠퍼스. UK 자격 + 현지 혼합.',
    note_zh: 'UCSI 集团新校区。UK 资格 + 本地混合。' },
  // 신규 12개
  'king-henry-viii': { ratio: 80, source: 'official',
    note_ko: 'King\'s Canterbury 자매학교. UK 본교 파견 + UK 자격 교사 중심.',
    note_zh: 'King\'s Canterbury 姊妹校。UK 总校派遣 + UK 资格教师为主。' },
  'adcote-matrix': { ratio: 72, source: 'official',
    note_ko: '영국 Adcote 자매학교. UK 자격 + 보딩 하우스마스터.',
    note_zh: '英国 Adcote 姊妹校。UK 资格 + 寄宿舍监。' },
  'eaton-kajang': { ratio: 35, source: 'community',
    note_ko: 'Cambridge 자격 + 말레이·인도 영어 교사 혼합.',
    note_zh: 'Cambridge 资格 + 马来 · 印度英语教师混合。' },
  'eaton-shah-alam': { ratio: 35, source: 'community',
    note_ko: 'Cambridge 자격 + 말레이·인도 영어 교사 혼합.',
    note_zh: 'Cambridge 资格 + 马来 · 印度英语教师混合。' },
  'sri-kdu-subang': { ratio: 55, source: 'community',
    note_ko: 'Sri KDU 본 캠퍼스. Cambridge + UK 자격 다수.',
    note_zh: 'Sri KDU 本校区。Cambridge + UK 资格多。' },
  'sri-kdu-klang': { ratio: 45, source: 'community',
    note_ko: 'Sri KDU 그룹 Klang. UK 자격 + 현지 혼합.',
    note_zh: 'Sri KDU 集团 Klang。UK 资格 + 本地混合。' },
  'ucsi-springhill': { ratio: 40, source: 'community',
    note_ko: 'UCSI 그룹. 보딩 운영 — UK·현지 혼합.',
    note_zh: 'UCSI 集团。寄宿运营 — UK · 本地混合。' },
  'tenby-tropicana-aman': { ratio: 45, source: 'community',
    note_ko: 'Tenby 그룹 신캠퍼스. UK 자격 + 현지 혼합.',
    note_zh: 'Tenby 集团新校区。UK 资格 + 本地混合。' },
  'tenby-setia-ecohill': { ratio: 40, source: 'community',
    note_ko: 'Tenby Semenyih. Cambridge + 현지 다수.',
    note_zh: 'Tenby 士毛月。Cambridge + 本地多。' },
  'maple-leaf-kingsley': { ratio: 60, source: 'official',
    note_ko: '캐나다 Ontario OSSD. 캐나다 자격 교사 다수.',
    note_zh: '加拿大 Ontario OSSD。加拿大资格教师多。' },
  'rocklin': { ratio: 30, source: 'community',
    note_ko: 'Cheras 가성비. UK 자격 + 현지·인도 혼합.',
    note_zh: 'Cheras 性价比。UK 资格 + 本地 · 印度混合。' },
  'concord': { ratio: 25, source: 'community',
    note_ko: 'PJ 가성비. 현지·필리핀·인도 영어 교사 다수.',
    note_zh: 'PJ 性价比。本地 · 菲律宾 · 印度英语教师多。' },

  // ─── 한국 ─────────────────────────────────────────────────────
  // 외국인학교 — 외국인 학생 대상 → 원어민 비율 매우 높음
  'sfs': { ratio: 95, source: 'official',
    note_ko: '서울 외국인학교 (1912 설립). 미국·캐나다 본토 교사 다수. WASC·NAIS 인증.',
    note_zh: '首尔外国人学校 (1912 创立)。美国 · 加拿大本土教师多。WASC · NAIS 认证。' },
  'yiss': { ratio: 90, source: 'official',
    note_ko: '용산국제학교. 미국·캐나다·UK 다수. 기독교계.',
    note_zh: '龙山国际学校。美国 · 加拿大 · 英国多。基督教系。' },
  'kis-seoul': { ratio: 90, source: 'official',
    note_ko: 'KIS Seoul. 미국·캐나다 IB 자격 교사 중심.',
    note_zh: 'KIS Seoul。美国 · 加拿大 IB 资格教师为主。' },
  'dwight-seoul': { ratio: 88, source: 'official',
    note_ko: '뉴욕 Dwight School 자매. IB World School. 미국·UK 다수.',
    note_zh: '纽约 Dwight School 姊妹校。IB World School。美国 · 英国多。' },
  'dulwich-seoul': { ratio: 92, source: 'official',
    note_ko: '런던 Dulwich College 자매. UK 본교 파견 + UK 자격.',
    note_zh: '伦敦 Dulwich College 姊妹校。UK 总校派遣 + UK 资格。' },
  'kis-pangyo': { ratio: 88, source: 'official',
    note_ko: 'KIS 그룹 판교 캠퍼스. 미국·캐나다 IB 자격.',
    note_zh: 'KIS 集团板桥校区。美国 · 加拿大 IB 资格。' },
  'gsis': { ratio: 75, source: 'community',
    note_ko: '경기외국어고등학교 (현재 GSIS). 미국·UK + 일부 한국 영어 교사.',
    note_zh: '京畿外国语高中 (现 GSIS)。美国 · 英国 + 部分韩国英语教师。' },
  'ics-pyeongtaek': { ratio: 85, source: 'official',
    note_ko: '주한미군 자녀 대상. 미국 자격 교사 다수.',
    note_zh: '驻韩美军子弟为主。美国资格教师多。' },
  'isb-busan': { ratio: 75, source: 'community',
    note_ko: '부산외국인학교. 미국·캐나다·호주 + 일부 현지.',
    note_zh: '釜山外国人学校。美国 · 加拿大 · 澳大利亚 + 部分本地。' },
  'dis-daegu': { ratio: 65, source: 'community',
    note_ko: '대구국제학교. 미국·UK + 한국 영어 교사 혼합.',
    note_zh: '大邱国际学校。美国 · 英国 + 韩国英语教师混合。' },
  'bfs': { ratio: 60, source: 'community',
    note_ko: '부산프랑스학교 (BFS). 프랑스·영어권 + 한국 교사.',
    note_zh: '釜山法国学校 (BFS)。法国 · 英语圈 + 韩国教师。' },
  // 국제학교 (제주·송도) — 내국인 입학 가능
  'nlcs-jeju': { ratio: 92, source: 'official',
    note_ko: '런던 NLCS 자매. UK 본교 파견. 영국 정통.',
    note_zh: '伦敦 NLCS 姊妹校。UK 总校派遣。英国正统。' },
  'kis-jeju': { ratio: 85, source: 'official',
    note_ko: 'KIS 그룹 제주. 미국·캐나다 IB.',
    note_zh: 'KIS 集团济州。美国 · 加拿大 IB。' },
  'bha': { ratio: 85, source: 'official',
    note_ko: 'Branksome Hall 캐나다 자매. 캐나다·UK 교사.',
    note_zh: 'Branksome Hall 加拿大姊妹校。加拿大 · 英国教师。' },
  'sja-jeju': { ratio: 88, source: 'official',
    note_ko: 'St Johnsbury Academy 미국 자매. 미국 자격 + 캐나다.',
    note_zh: 'St Johnsbury Academy 美国姊妹校。美国资格 + 加拿大。' },
  'chadwick-songdo': { ratio: 87, source: 'official',
    note_ko: 'Chadwick LA 자매. 미국 자격 교사. IB.',
    note_zh: 'Chadwick LA 姊妹校。美国资格教师。IB。' },
};
