import type { APIRoute } from 'astro';

// robots.txt — 가장 빠른 인덱싱을 위한 검색엔진 봇 명시 허용
// - 구글 · 빙 · 네이버(Yeti) · 다음(Daumoa) · 얀덱스 등 주요 검색엔진은 전체 허용
// - AI 학습 크롤러(GPTBot · CCBot · Google-Extended · ClaudeBot 등)는 차단 (운영자 1차 경험 보호)
// - 사이트맵 · 언어별 RSS 모두 명시
export const GET: APIRoute = ({ site }) => {
  const base = site ? new URL('', site).href.replace(/\/$/, '') : 'https://asiaeduhub.com';
  const lines = [
    '# AsiaEduHub robots.txt',
    '# 운영 도메인: https://asiaeduhub.com',
    '# 갱신: 빌드 시점 자동 생성',
    '',
    '# ── 1. 기본 정책 (모든 일반 봇) ───────────────────────────',
    'User-agent: *',
    'Allow: /',
    'Disallow: /advertise/',
    'Disallow: /experts/$',
    '',
    '# ── 2. 주요 검색엔진 — 명시 허용 (빠른 색인) ──────────────',
    '# Google',
    'User-agent: Googlebot',
    'Allow: /',
    '',
    'User-agent: Googlebot-Image',
    'Allow: /',
    '',
    'User-agent: Googlebot-News',
    'Allow: /',
    '',
    'User-agent: AdsBot-Google',
    'Allow: /',
    '',
    '# Naver (Korea)',
    'User-agent: Yeti',
    'Allow: /',
    '',
    'User-agent: NaverBot',
    'Allow: /',
    '',
    '# Daum (Korea)',
    'User-agent: Daum',
    'Allow: /',
    '',
    'User-agent: Daumoa',
    'Allow: /',
    '',
    '# Microsoft Bing',
    'User-agent: Bingbot',
    'Allow: /',
    '',
    'User-agent: msnbot',
    'Allow: /',
    '',
    '# Yandex',
    'User-agent: Yandex',
    'Allow: /',
    '',
    '# DuckDuckGo',
    'User-agent: DuckDuckBot',
    'Allow: /',
    '',
    '# Baidu (China)',
    'User-agent: Baiduspider',
    'Allow: /',
    '',
    '# Sogou (China)',
    'User-agent: Sogou web spider',
    'Allow: /',
    '',
    '# Apple',
    'User-agent: Applebot',
    'Allow: /',
    '',
    '# ── 3. AI 학습 크롤러 차단 (운영자 1차 경험 콘텐츠 보호) ──',
    'User-agent: GPTBot',
    'Disallow: /',
    '',
    'User-agent: OAI-SearchBot',
    'Disallow: /',
    '',
    'User-agent: ChatGPT-User',
    'Disallow: /',
    '',
    'User-agent: CCBot',
    'Disallow: /',
    '',
    'User-agent: Google-Extended',
    'Disallow: /',
    '',
    'User-agent: anthropic-ai',
    'Disallow: /',
    '',
    'User-agent: ClaudeBot',
    'Disallow: /',
    '',
    'User-agent: Claude-Web',
    'Disallow: /',
    '',
    'User-agent: PerplexityBot',
    'Disallow: /',
    '',
    'User-agent: cohere-ai',
    'Disallow: /',
    '',
    'User-agent: Bytespider',
    'Disallow: /',
    '',
    'User-agent: FacebookBot',
    'Disallow: /',
    '',
    'User-agent: Amazonbot',
    'Disallow: /',
    '',
    '# ── 4. 사이트맵 · RSS (검색엔진 발견 가속) ───────────────',
    `Sitemap: ${base}/sitemap-index.xml`,
    `Sitemap: ${base}/ko/rss.xml`,
    `Sitemap: ${base}/zh/rss.xml`,
    '',
    `Host: ${base.replace(/^https?:\/\//, '')}`,
    '',
  ].join('\n');

  return new Response(lines, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // 검색봇이 변경을 빠르게 확인하도록 짧은 캐시
      'Cache-Control': 'public, max-age=300, s-maxage=300',
    },
  });
};
